### ISSUE TITLE
For some words , API is returning lowercase string.

### ISSUE THREAD

**Issue by HemDutt** [waynehartman/GoogleTranslationAPI#1]
Hi,

I am using the wrapper for my translation in Cocoa Code. It works great.
Only occasionally for some words , the translated string is always in lower case.

For example when I translate "Images" to Spanish

Using API : I get "imágenes"
Using Web App of Google : I get "Imágenes"

Why is this difference?

Regards,
Hem Dutt

**Comment by waynehartman** [comment]
Fortunately, I speak Spanish. :) There is no difference.

That said, without looking at how the web app implemented the calls, it's possible that there is some additional option to preserve the sentence casing of the input even when an actual, fully constructed sentence isn't detected. Have you tried using a full English sentence to see if it preserves the casing?

**Comment by HemDutt** [comment]
We often need one word translations for buttons and labels and doing multiple languages at the same time.

When we translate the single english word, **Image**, via the api, all languages correctly return a translation with a capital to start, with the exception of Spanish which returns lower case. 
However, if we go directly to google translate site, the Spanish translation has a capital. 

Why is it not returning what is available @google translate site? Any thoughts? Otherwise, I guess we can programmatically check for for case problems. 

When we translate the OK in english via the api, all languages return correctly, except in french it returned D&#39;accord.... rather than D'accord. Unlike lower case, how do we deal/recognize errors/substitutes for special characters?

**Comment by waynehartman** [comment]
I'm not sure why Google's API differs to what it displays on the web. To compensate, you might consider using the NSString API `localizedCapitalizedString` to appropriately capitalize and see if that produces the result you desire.
